some_str = str(input())
print(some_str[2])
print(some_str[-2])
print(some_str[0:-5])
print(some_str[:-2])
print(some_str[::2])
print(some_str[1::2])
print(some_str[::-1])
print(some_str[::-2])
print(len(some_str))
